### ISSUE TITLE
Mettre en place une BDD

### ISSUE THREAD

**Issue by Brounchy** [Invivoo/ViV-Wallet#114]

**Comment by Julien-Molina** [comment]
Pour l'UAT ou la prod ?

**Comment by Brounchy** [comment]
On peut commencer par l'uat et on verra ensuite pour la prod, ça te va ?

**Comment by Brounchy** [comment]
2 solutions : 
Tu préfères mettre : 


	

- --spring.datasource.url=$SqlServerUrl --spring.datasource.username=$SqlServerUsername --spring.datasource.password=$SqlServerPassword --spring.datasource.driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver --spring.jpa.database-platform: org.hibernate.dialect.SQLServer2012Dialect --spring.flyway.enabled=true 
ou
- --spring.datasource.url=$SqlServerUrl --spring.datasource.username=$SqlServerUsername --spring.datasource.password=$SqlServerPassword --spring.profiles.active=sqlServer
