### ISSUE TITLE
Ajouter un variable d'environement ainsi que la configuration depuis le chart helm pour la configuration de l'url X4B.

### ISSUE THREAD

**Issue by Julien-Molina** [Invivoo/ViV-Wallet#138]

**Comment by nicolaserny** [comment]
Some ideas to solve this issue:
https://medium.com/js-dojo/vue-js-runtime-environment-variables-807fa8f68665
https://stackoverflow.com/questions/53010064/pass-environment-variable-into-a-vue-app-at-runtime
