### ISSUE TITLE
En tant que collaborateur Invivoo, je veux pouvoir consulter l'évolution de mon wallet de VIV depuis mon arrivée chez Invivoo

### ISSUE THREAD

**Issue by Brounchy** [Invivoo/ViV-Wallet#14]
### En tant que collaborateur Invivoo, je veux pouvoir consulter l'évolution de mon wallet de VIV depuis mon arrivée chez Invivoo

Chaque collaborateurs devra pouvoir consulter depuis l'interface développée dans https://github.com/Invivoo/ViV-Wallet/issues/24 : 
- Les paiements 
- Le Solde (VIV non transformés en paie) 
- La totalité des VIV générés 

**Tests**

  - Balance :
    - Given user
    - When calling GET api/v1/users/{userId}/balance
    - Then get user balance
  - User Actions
    - Given a user 
    - When calling GET api/v1/users/{userId}/actions
    - Then get user actions sorted by CreationDate DESC
  - Payments
    - Given a user 
    - When calling GET api/v1/users/{userId}/payments
    - Then get user payment history by PaymentDate DESC

**Comment by ChristopheGodard** [comment]
Pull request: https://github.com/Invivoo/ViV-Wallet/pull/60
