### ISSUE TITLE
En tant que collaborateur Invivoo, je veux pouvoir me connecter à l'application VIV Wallet en utilisant mes identifiants Office 365

### ISSUE THREAD

**Issue by maurelio1234** [Invivoo/ViV-Wallet#22]
**Related issue(s):** #13

**Mock up(s):** 

- Login page:

![image](https://user-images.githubusercontent.com/6065520/69917623-36fe2100-1468-11ea-8d0b-871ebeab523c.png)

**Scenarios to support:**

- Connect to the application using Office 365

**In scope:**
- Retrieve JWT token and store it along with other info about user in LoginService
- Configure router
   - `/login` for the login page
   - `/logout` to disconnect (redirect to the login page)
   - Redirect to the login page when user is not connected
   - Redirect to `/home` after

**Comment by nicolaserny** [comment]
As the project will be part of X4B, we just have to use the x4b-ui banner. It includes office365 authentication.
Scope: x4b-ui integration.

**Comment by maurelio1234** [comment]
Todo

- [ ] Use french
- [ ] make login/apps urls configurable

**Comment by maurelio1234** [comment]
- [ ] Decode token
